### ISSUE TITLE
Como designar mas memoria a linux una vez ya instalado

### ISSUE THREAD

**Issue by ssaniefrancc** [weskerty/LinuxOneClick#1]
Cómo puedo aumentar el almacenamiento utilizado por linux?

**Comment by weskerty** [comment]
Te funciono el Script?
Justo estaba cambiandolo a otras cosas y borre la Descarga Principal.
Si 35GB te parecia poco, ahora lo ajuste a 25.

Para aumentar la memoria del VDI es complicado, Debes usar VirtualBox y luego desde un Gestor de Discos como DiskGenius Agrandar el Tamaño de la particion ext4 del VDI.
![image](https://github.com/user-attachments/assets/975e6455-ffb2-489a-a4e7-118a1c66008c)
Sin DiskGenius Deberas Agrandar la particion con VirtualBox, luego crear una maquina virtual en VirtualBox y agregar el VDI e iniciar un LiveCD de gparted o alguna otra distro, abrir el gestor de discos y agrandar el tamaño de la particion ext4.

Pensaba hacer un script para aumentar el tamaño facilmente desde windows, pero creo deberia haber el disco en VHD e instalarlo en btrfs para que se pueda controlar con un driver de Windows. Luego veo si puedo hacerlo o almenos una guia para hacerlo.

**Comment by ssaniefrancc** [comment]
> Te funciono el Script? Justo estaba cambiandolo a otras cosas y borre la Descarga Principal. Si 35GB te parecia poco, ahora lo ajuste a 25 por que me gustaria que funcione con esas Notebooks que son populares en mi pais que tienen 60GB, 4RAM y un Celerom
> 
> Para aumentar la memoria del VDI es complicado, Debes usar VirtualBox y luego desde un Gestor de Discos como DiskGenius Agrandar el Tamaño de la particion ext4 del VDI. ![image](https://private-user-images.githubusercontent.com/82781997/356385435-975e6455-ffb2-489a-a4e7-118a1c66008c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTUxODQsIm5iZiI6MTcyMzE1NDg4NCwicGF0aCI6Ii84Mjc4MTk5Ny8zNTYzODU0MzUtOTc1ZTY0NTUtZmZiMi00ODlhLWE0ZTctMTE4YTFjNjYwMDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIyMDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxY2Y5MmE3OTU1YzVjYjI5ZGMyMTM0MTNlNGIwODVjOGQwYzZmYTE0OTc1MTM1OTcyYTk2ZjExYmU5YTkzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91VpBreAnNKEyHZpolEUAMXnxJdGKPGpu8TXLEqMbnk) Sin DiskGenius Deberas Agrandar la particion con VirtualBox, luego crear una maquina virtual en VirtualBox y agregar el VDI e iniciar un LiveCD de gparted o alguna otra distro, abrir el gestor de discos y agrandar el tamaño de la particion ext4.
> 
> Pensaba hacer un script para aumentar el tamaño facilmente desde windows, pero creo deberia haber el disco en VHD e instalarlo en btrfs para que se pueda controlar con un driver de Windows. Luego veo si puedo hacerlo o almenos una guia para hacerlo.

Gracias, voy a probar ahora, estaba revisando la website oficial pero se me perdio la parte que hablaba sobre eso
